version: "3.1"

services:
  db:
    image: mysql:8.0.0
    command: --default-authentication-plugin=mysql_native_password --init-file /mysql_init/init.sql
    restart: always
    volumes:
      - ./:/mysql_init
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
